openapi: 3.0.0
info:
  title: chainid
  version: '1.0'
  contact:
    name: ChainId
    url: Chainid.io
    email: indo@chainid.io
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        '':
          type: string
